/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.project.view.form;

import java.util.List;
import javax.swing.plaf.synth.ColorType;
import ps.project.controller.Controller;
import ps.project.domain.City;
import ps.project.view.form.util.FrmMode;

/**
 *
 * @author saska
 */
public class FrmCustomer extends javax.swing.JDialog {

    /**
     * Creates new form FrmCustomer
     */
    FrmMode frmMode;

    public FrmCustomer(java.awt.Frame parent, boolean modal, FrmMode mode) {
        super(parent, modal);
        initComponents();
        frmMode = mode;
        System.out.println(frmMode);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNaturalPerson = new javax.swing.JPanel();
        lblFullname = new javax.swing.JLabel();
        lblPersonalNumber = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPersonalNumber = new javax.swing.JTextField();
        panelLegalPerson = new javax.swing.JPanel();
        lblCompanyName = new javax.swing.JLabel();
        lblTin = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtTin = new javax.swing.JTextField();
        lblCompanyNumber = new javax.swing.JLabel();
        txtCompanyNumber = new javax.swing.JTextField();
        lblTittle = new javax.swing.JLabel();
        panelOtherInformations = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPostalCode = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPostalCode = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        cbCity = new javax.swing.JComboBox<>();
        btnSaveCustomer = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos kupca");

        panelNaturalPerson.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fizičko lice:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 11))); // NOI18N

        lblFullname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblFullname.setText("Ime i prezime:");

        lblPersonalNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblPersonalNumber.setText("JMBG:");

        txtFullName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtPersonalNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelNaturalPersonLayout = new javax.swing.GroupLayout(panelNaturalPerson);
        panelNaturalPerson.setLayout(panelNaturalPersonLayout);
        panelNaturalPersonLayout.setHorizontalGroup(
            panelNaturalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNaturalPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNaturalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNaturalPersonLayout.createSequentialGroup()
                        .addComponent(lblFullname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(panelNaturalPersonLayout.createSequentialGroup()
                        .addComponent(lblPersonalNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPersonalNumber)))
                .addContainerGap())
        );
        panelNaturalPersonLayout.setVerticalGroup(
            panelNaturalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNaturalPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNaturalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNaturalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPersonalNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPersonalNumber))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelLegalPerson.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pravno lice:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        lblCompanyName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCompanyName.setText("Naziv:");

        lblTin.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblTin.setText("PIB:");

        txtCompanyName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtTin.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        lblCompanyNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCompanyNumber.setText("MB (Matični broj frime):");

        txtCompanyNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelLegalPersonLayout = new javax.swing.GroupLayout(panelLegalPerson);
        panelLegalPerson.setLayout(panelLegalPersonLayout);
        panelLegalPersonLayout.setHorizontalGroup(
            panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLegalPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLegalPersonLayout.createSequentialGroup()
                        .addComponent(lblCompanyName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCompanyName))
                    .addGroup(panelLegalPersonLayout.createSequentialGroup()
                        .addComponent(lblTin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTin))
                    .addGroup(panelLegalPersonLayout.createSequentialGroup()
                        .addComponent(lblCompanyNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCompanyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLegalPersonLayout.setVerticalGroup(
            panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLegalPersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyName)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLegalPersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompanyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompanyNumber))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblTittle.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTittle.setText("Molimo unesite podatke o kupcu...");

        lblId.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblId.setText("Id:");

        lblPhoneNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblPhoneNumber.setText("Telefon:");

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblEmail.setText("E-mail:");

        lblAddress.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblAddress.setText("Adresa:");

        lblPostalCode.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblPostalCode.setText("Poštanski broj:");

        txtId.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        txtPostalCode.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        lblCity.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCity.setText("Grad:");

        javax.swing.GroupLayout panelOtherInformationsLayout = new javax.swing.GroupLayout(panelOtherInformations);
        panelOtherInformations.setLayout(panelOtherInformationsLayout);
        panelOtherInformationsLayout.setHorizontalGroup(
            panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress))
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId))
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumber))
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblPostalCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOtherInformationsLayout.setVerticalGroup(
            panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtherInformationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOtherInformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSaveCustomer.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnSaveCustomer.setText("Sačuvaj");
        btnSaveCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCustomerActionPerformed(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelOtherInformations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelLegalPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelNaturalPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTittle)
                    .addComponent(btnSaveCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOtherInformations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLegalPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelNaturalPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCustomerActionPerformed
        String phoneNumber = txtPhoneNumber.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();
        Long postalCode = new Long(txtPostalCode.getText());
        City city = (City) cbCity.getSelectedItem();

        //IF NATURAL_PERSON
        String fullname = "";
        String personalNumber = "";
        //IF LEGAL_PERSON
        String companyName = "";
        String tin = "";
        String companyNumber = "";

        //validacija
        if (frmMode.equals(FrmMode.NATURAL_PERSON)) {
            fullname = txtFullName.getText().trim();
            personalNumber = txtPersonalNumber.getText().trim();
        }

        if (frmMode.equals(FrmMode.LEGAL_PERSON)) {
            companyName = txtCompanyName.getText().trim();
            tin = txtTin.getText().trim();
            companyNumber = txtCompanyNumber.getText().trim();
        }

        if (!phoneNumber.isEmpty() && !email.isEmpty() && !address.isEmpty() && !postalCode.equals(null) ) {
            if (frmMode.equals(FrmMode.NATURAL_PERSON)) {
                if (fullname.isEmpty() || personalNumber.isEmpty()) {
                    lblWarning.setText("Sva polja su obavezna!");
                 
                } else if (frmMode.equals(FrmMode.LEGAL_PERSON)) {
                    if (companyName.isEmpty() || tin.isEmpty() || companyNumber.isEmpty()) {
                        lblWarning.setText("Sva polja su obavezna!");
                    } 
                }
            }
           
        } else {
            lblWarning.setText("Sva polja su obavezna!");
        }


    }//GEN-LAST:event_btnSaveCustomerActionPerformed

    private void prepareView() {
        setLocationRelativeTo(null);
        txtId.setEnabled(false);
      //  fillCbCity();
        setupComponents();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCustomer;
    private javax.swing.JComboBox<Object> cbCity;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblCompanyNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPersonalNumber;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblTin;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel panelLegalPerson;
    private javax.swing.JPanel panelNaturalPerson;
    private javax.swing.JPanel panelOtherInformations;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCompanyNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPersonalNumber;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtTin;
    // End of variables declaration//GEN-END:variables

    private void setupComponents() {
        switch (frmMode) {
            case NATURAL_PERSON:
                panelLegalPerson.setVisible(false);
                break;
            case LEGAL_PERSON:
                panelNaturalPerson.setVisible(false);
                break;
        }
    }

   /* private void fillCbCity() {
        List<City> cities = Controller.getInstance().getAllCities();
        for (City city : cities) {
            cbCity.addItem(city);
        }
    }*/

}
