/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.project.view.form;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.w3c.dom.ls.DOMImplementationLS;
import ps.project.controller.Controller;
import ps.project.view.form.util.FrmMode;

/**
 *
 * @author saska
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    FrmMode frmMode;

    public FrmMain(FrmMode mode) {
        initComponents();
        frmMode = mode;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoggedSeller = new javax.swing.JLabel();
        btnNaturalPerson = new javax.swing.JButton();
        btnLegalPerson = new javax.swing.JButton();
        btnMainContracts = new javax.swing.JButton();
        lblUserIcon = new javax.swing.JLabel();
        btnMainCustomers = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnMainAutomobiles = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Početna stranica");
        setSize(new java.awt.Dimension(1366, 745));
        getContentPane().setLayout(null);

        lblLoggedSeller.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblLoggedSeller.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lblLoggedSeller);
        lblLoggedSeller.setBounds(1150, 0, 180, 20);

        btnNaturalPerson.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnNaturalPerson.setText("FIZIČKA LICA");
        btnNaturalPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaturalPersonActionPerformed(evt);
            }
        });
        getContentPane().add(btnNaturalPerson);
        btnNaturalPerson.setBounds(540, 240, 230, 80);

        btnLegalPerson.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnLegalPerson.setText("PRAVNA LICA");
        btnLegalPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLegalPersonActionPerformed(evt);
            }
        });
        getContentPane().add(btnLegalPerson);
        btnLegalPerson.setBounds(540, 130, 230, 80);

        btnMainContracts.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMainContracts.setText("UGOVORI");
        btnMainContracts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainContractsActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainContracts);
        btnMainContracts.setBounds(550, 160, 210, 140);

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps/project/img/user.png"))); // NOI18N
        getContentPane().add(lblUserIcon);
        lblUserIcon.setBounds(1340, 0, 20, 20);

        btnMainCustomers.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMainCustomers.setText("KUPCI");
        btnMainCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainCustomers);
        btnMainCustomers.setBounds(110, 160, 210, 140);

        lblWelcomeMessage.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblWelcomeMessage.setText("Dobro došli u autocentar Škoda!");
        getContentPane().add(lblWelcomeMessage);
        lblWelcomeMessage.setBounds(520, 10, 290, 26);

        btnMainAutomobiles.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMainAutomobiles.setText("AUTOMOBILI");
        btnMainAutomobiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainAutomobilesActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainAutomobiles);
        btnMainAutomobiles.setBounds(1020, 160, 210, 140);

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnBack.setText("NAZAD");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 20, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainCustomersActionPerformed
        frmMode = FrmMode.CUSTOMER_OPTION;
        setupComponents();

    }//GEN-LAST:event_btnMainCustomersActionPerformed

    private void btnMainContractsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainContractsActionPerformed
        System.out.println("Nije jos dodata forma ugovori");
    }//GEN-LAST:event_btnMainContractsActionPerformed

    private void btnMainAutomobilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainAutomobilesActionPerformed
        JDialog frmAutomobile = new FrmAutomobile(this, true);
        frmAutomobile.setVisible(true);
    }//GEN-LAST:event_btnMainAutomobilesActionPerformed

    private void btnNaturalPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaturalPersonActionPerformed
        new FrmOverview(FrmMode.NATURAL_PERSON).setVisible(true);
    }//GEN-LAST:event_btnNaturalPersonActionPerformed

    private void btnLegalPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLegalPersonActionPerformed
        new FrmOverview(FrmMode.LEGAL_PERSON).setVisible(true);
    }//GEN-LAST:event_btnLegalPersonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        frmMode = FrmMode.MAIN_OPTION;
        setupComponents();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLegalPerson;
    private javax.swing.JButton btnMainAutomobiles;
    private javax.swing.JButton btnMainContracts;
    private javax.swing.JButton btnMainCustomers;
    private javax.swing.JButton btnNaturalPerson;
    private javax.swing.JLabel lblLoggedSeller;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblWelcomeMessage;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        //Pozicioniranje forme

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        this.setLocation(x, y);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        //Ulogovani prodavac
        lblLoggedSeller.setText(Controller.getInstance().getLoggedSeller().getFirstNname() + " " + Controller.getInstance().getLoggedSeller().getLastName());
        setupComponents();
    }

    private void setupComponents() {
        switch (frmMode) {
            case MAIN_OPTION:
                lblLoggedSeller.setVisible(true);
                lblUserIcon.setVisible(true);
                lblWelcomeMessage.setVisible(true);
                
                
                btnMainCustomers.setVisible(true);
                btnMainAutomobiles.setVisible(true);
                btnMainContracts.setVisible(true);

                btnLegalPerson.setVisible(false);
                btnNaturalPerson.setVisible(false);
                btnBack.setVisible(false);
                break;
            case CUSTOMER_OPTION:
                lblLoggedSeller.setVisible(true);
                lblUserIcon.setVisible(true);
                lblWelcomeMessage.setVisible(false);
                
                btnMainCustomers.setVisible(false);
                btnMainAutomobiles.setVisible(false);
                btnMainContracts.setVisible(false);

                btnLegalPerson.setVisible(true);
                btnNaturalPerson.setVisible(true);
                btnBack.setVisible(true);

                break;

        }
    }
}
